---
- name: install HTTP server
  hosts: g1
  become: yes
  
  tasks:
    - name: install HTTPD
      yum:
        name: httpd
        state: present
      when: ansible_distribution == "Debian"

    - name: start Httpd
      service:
       name: httpd
       state: started
      when: ansible_distribution == "Debian"
   
    - name: Enable httpd
      service:
       name: httpd
       enabled: yes 
      when: ansible_distribution == "CentOS"
  
    - name: install Apache2
      apt:
        name: apache2
        state: present
      when: ansible_distribution == "CentOS"

    - name: start apache2
      service:
       name: apache2
       state: started
      when: ansible_distribution == "Amazon"

    - name: Enable apache2
      service:
       name: apache2
       enabled: yes      
      when: ansible_distribution == "ubuntu"
...
