---
- name: Variable Demo
  hosts: g1
  become: yes
  vars:
  myusername: Victory
 
  tasks:
    - name: Update static page
      template:
        src: dynamic.j2
        dest: /var/www/html/dynamic.html
...